services:
  backend:
    build: ./butaman-backend
    container_name: butaman-backend
    working_dir: /app
    volumes:
      - ./butaman-backend:/app
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command: cargo run -- --web # 本番は `cargo run -- --web` にしてもOK

  frontend:
    build:
      context: ./butaman-frontend
    container_name: butaman-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend