services:
  rust-dev:
    build: .
    container_name: rust-dev
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command: /bin/bash
    networks:
      - ipv6net

networks:
  ipv6net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "fd00:dead:beef::/64"
