services:
  rust-dev:
    build: .
    container_name: rust-dev
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.ssh:/root/.ssh:ro
    stdin_open: true
    tty: true
    command: /bin/bash
